# Generated by Django 6.1.1 on 2026-09-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='meetings/audio/'),
        ),
    ]
