# Generated by Django 6.1.1 on 2026-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
