# Generated by Django 6.1.1 on 2026-09-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='action_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='decisions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='key_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
