# Generated by Django 6.1.1 on 2026-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_action_items_meeting_decisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
