# Generated by Django 6.1.1 on 2026-09-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
