# Generated by Django 6.1.1 on 2026-09-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
